### ISSUE TITLE
Errors in package

### ISSUE THREAD

**Issue by ariran5** [gxlmyacc/react-view-router#10]
Could not find dependency: 'core-js' relative to '/node_modules/react-view-router/esm/index.js'

after build scripts go to esm folder, but code in es folder

**Comment by ariran5** [comment]
https://codesandbox.io/s/naughty-rhodes-nf5u8?file=/src/App.js

**Comment by ariran5** [comment]
and demo not work

**Comment by gxlmyacc** [comment]
thanks your feedback, please install core-js@2, and I will add `core-js` to package.json at next version

**Comment by gxlmyacc** [comment]
> Could not find dependency: 'core-js' relative to '/node_modules/react-view-router/esm/index.js'
> 
> after build scripts go to esm folder, but code in es folder

thanks your feedback, please install core-js@2, and I will add core-js to package.json at next version

**Comment by gxlmyacc** [comment]
> and demo not work



> Could not find dependency: 'core-js' relative to '/node_modules/react-view-router/esm/index.js'
> 
> after build scripts go to esm folder, but code in es folder

please try react-view-router@2.1.4

**Comment by gxlmyacc** [comment]
> and demo not work

demo was updated, please retry
