### ISSUE TITLE
How to have a nested route with a root path?

### ISSUE THREAD

**Issue by diavrank** [gxlmyacc/react-view-router#30]
Hello, I started to implement this routing tool in a react app, so, I am trying to replicate the routing configuration from another Vue app that I have made, however, I am having an issue with **nested routes**. To make this more understandable, this is my routing configuration:

_routes.ts_

```ts
import { normalizeRoutes } from 'react-view-router';
import LayoutSPA from '/imports/ui/layouts/LayoutSPA';
import LayoutAuth from '/imports/ui/layouts/LayoutAuth';
import Login from '/imports/ui/views/Auth/Login';
import ForgotPassword from '/imports/ui/views/Auth/ForgotPassword';

export default normalizeRoutes([
	{ path: '/', index: 'home' },
	{
		path: '/home',
		name: 'home',
		component: LayoutSPA
	},
	{
		path: '/login',
		component: LayoutAuth,
		children: [
			{
				name: 'forgotPassword',
				path: '/forgot-password',
				components: {
					sectionView: ForgotPassword
				}
			},
			{
				name: 'login',
				path: '',
				components: {
					sectionView: Login
				}
			}
		]
	}
]);
```

In Vue 2 apps, I can use nested views with root paths, however, in the React app, if I want to access to **ForgotPassword** view, I have to put the **/login/forgot-password** path, whereas in Vue you can put only **/forgot-password** and it will work because the pathname for ForgotPassword view starts with a **slash ( / )**. So, I was wondering if this can be possible somehow?

On the other hand, I have 2 questions more:

What is the difference between **index** and **redirect** fields of a route?
What is the **name** property used for? (I use it in Vue apps to identify the route and it was used to navigate between routes, as an alternative field from the path field)

Hope you can help me with this :) .

**Comment by gxlmyacc** [comment]
may be you can use `router.push('[forgotPassword]')`; when the path has `[]`, router will resolve it with 'name' in the routing configuration.

`index` won't change the location.href, and `redirect` will do that.
