### ISSUE TITLE
How to inject transitions?

### ISSUE THREAD

**Issue by diavrank** [gxlmyacc/react-view-router#49]
Hi @gxlmyacc , I am trying to use this [plugin](http://reactcommunity.org/react-transition-group/with-react-router) with `react-view-router` to inject transitions when a route is changed. The plugin is inspired by the [vue transition modes](https://vuejs.org/v2/guide/transitions.html#Transition-Modes) and it was designed to work with React Router, so, I guess that it could work as well with `react-view-router` since this router is based on React Router. An example with React Router is the following code:

````jsx
<Route key={path} exact path={path}>
              {({ match }) => (
                <CSSTransition
                  in={match != null}
                  timeout={300}
                  classNames="page"
                  unmountOnExit
                >
                  <div className="page">
                    <Component />
                  </div>
                </CSSTransition>
              )}
            </Route>
````

So, with react-view-router I have this code:

````jsx
<CSSTransition in={false} // "in" prop should have a condition as value.
timeout={300} classNames="sectionView" unmountOnExit>
                            <div className="sectionView">
                                <RouterView name="sectionView" />
                            </div>
                        </CSSTransition>
````

So, I'm still figuring out where to take the `match` variable to inject the condition `match !== null`.

You can see the full example with React Router [here](http://reactcommunity.org/react-transition-group/with-react-router).

Is there a way to achieve it?

**Comment by diavrank** [comment]
I could solve it by using the `useRouteChanged` hook to simulate the match variable. Here is the code:


````jsx
...
import { Route, RouterView, useRouteChanged } from 'react-view-router';
...
    const [isChangedRoute, setIsChangedRoute] = useState<Route | null>(router.currentRoute);

    useRouteChanged(router, () => {
        setIsChangedRoute(null);
        console.log('router: ', router.currentRoute);
        setIsChangedRoute(router.currentRoute);
    });
...
<CSSTransition in={isChangedRoute !== null} timeout={500} classNames="page" unmountOnExit>
      <div className="page">
          <RouterView name="sectionView" />
      </div>
  </CSSTransition>
...

````

**Comment by gxlmyacc** [comment]
you maybe can use this RouterView prop:
` <RouterView
  router={router}
  fallback={<Loading className="page-loading" text="loading" />}
  container={(result, route) => (
    <SwitchTransition>
      <CSSTransition
        key={route.path}
        addEndListener={(node, done) => node.addEventListener('transitionend', done, false)}
        classNames="fade"
      >
        {result}
      </CSSTransition>
    </SwitchTransition>
  )}
/> `

**Comment by diavrank** [comment]
Thank you! It works as well.

**Comment by diavrank** [comment]
Hi, only to complement your example, it is needed to add a `div` tag over the result variable in order to make working both transitions (enter and exit). I share the solution:

````jsx
<RouterView
        name="sectionView"
        container={(result: any, route: any) => (
            <SwitchTransition mode="out-in">
                <CSSTransition
                    key={route.path}
                    addEndListener={(node, done) => node.addEventListener('transitionend', done, false)}
                    classNames="section-view"
                >
                    <div>{result}</div>
                </CSSTransition>
            </SwitchTransition>
        )}
    />
````

**Comment by gxlmyacc** [comment]
Thank you for your solution
