### ISSUE TITLE
`global` is not defined

### ISSUE THREAD

**Issue by trentfridey** [gxlmyacc/react-view-router#76]
After installing and running, the console throws an error

```
Uncaught ReferenceError: global is not defined
    <anonymous> global.ts:5
```

It looks like global.ts references `global` and it is not defined. Maybe you meant to use `globalThis`?
Thanks

**Comment by gxlmyacc** [comment]
yes, you're right. please try react-view-router@2.2.1, I updated global to globalThis

**Comment by trentfridey** [comment]
Thanks, I updated to 2.2.1 and the issue is no longer occurring.
